# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process (Ctrl-C to close and restart the server).

# Basic Site Settings
locale                   : "en-US"
title                    : "Junteng Liu"
title_separator          : "-"
name                     : "Junteng Liu"
description              : " "
url                      : "https://drrillm-ci.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/LJT-Homepage" # the subpath of your site, e.g. "/blog". Leave blank if you have a domain name

# Site Author (this displays on the side)
author:
  name             : "Junteng Liu"
  avatar           : "header.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "First-year PhD candidate at HKUST NLP Group."
  location         : "Hong Kong"
  employer         : "Hong Kong University of Science and Technology"
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  email            : "jliugi@connect.ust.hk"
  researchgate     : # profile URL
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "Vicent0205"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         :
  orcid            : #"http://orcid.org/yourorcid"
  pinterest        :
  soundcloud       :
  stackoverflow    : #"http://stackoverflow.com/users/123456/username"
  steam            :
  tumblr           :
  twitter          : "junteng88716710"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .DS_Store
  - .idea
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true

category_archive:
  path: /categories/
tag_archive:
  path: /tags/

# Set Sass values
sass:
  sass_dir: _sass
  style: compressed

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# These settings change the behavior of Sass/SCSS file processing
# See https://jekyllrb.com/docs/configuration/options/#build-settings

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

